#!/bin/bash

#run as root
[ $(id -u) != 0 ] && exec sudo $0

function ctrl_c() {
	echo "** Trapped CTRL-C: returning DNS cache to normal logging"
	killall mDNSResponder #restore default log levels to speed up syslog
	discoveryutil loglevel Basic
	discoveryutil logclass Everything
	kill $!
	echo "Should see $(hostname -s).local with TTL of 125 and with local interface names in the results, otherwise SPS server is retaining mirror record post-wake!"
	dns-sd -G v4v6 $(hostname -s).local &
	sleep 3 #dns-sd is clingy..
	exit 
}

function ctrl_t() {
	echo "** Trapped CTRL-T: going to sleep to trigger a SPS registration! Will wake up 15 secs later..."
	pmset relative wake 15; pmset sleepnow
}

if (launchctl blame system/com.apple.networking.discoveryd > /dev/null); then # OSX 10.10 Yosemite
	launchctl stop com.apple.networking.discoveryd
	( sleep 3
		discoveryutil lognoclass Everything
		discoveryutil logclass SleepProxy
		discoveryutil logclass Network
		discoveryutil logclass Packets
		#discoveryutil logclass DNSResolver #some sps-related "registration" messages, but a lot of generic app dns activity
		discoveryutil loglevel VeryDetailed
	) &
	syslog -w 0 -k Sender discoveryd </dev/null &
else
	#INFO dumps state
	#USR1 detail logs
	#USR2 per-query/packet logs
	killall mDNSResponder
	( sleep 3
		killall -INFO mDNSResponder
		killall -USR1 mDNSResponder
		#killall -USR2 mDNSResponder
	) &
	syslog -c mDNSResponder id #drop syslog debug filter bits
	syslog -w 0 -k Sender mDNSResponder | egrep 'Registered|WOMP|BeginSleepProcessing|goodbyes|SPS|SleepProxyServer' </dev/null & #logtail
fi

trap ctrl_c INT
trap ctrl_t INFO #BSD only :-(
trap ctrl_t TSTP
trap -- '' SIGTERM
echo "press CTRL-C to exit logtail and restore DNS cacher to normal logging. CTRL-T to sleep cycle this Mac"
	
while (true); do wait $!; done #watch syslog proc in background and listen for traps
kill $! #failsafe
