#!/usr/bin/env python

import gevent.monkey
gevent.monkey.patch_all()

from functools import partial

from sleepproxy import mdns, dnsserve

mdns.register_service(
    {
        'name': '10-34-10-70 SleepProxyServer', #<Type>-<Portability>-<MarginalPower>-<TotalPower> <PrettyName>
        #   http://www.opensource.apple.com/source/mDNSResponder/mDNSResponder-522.1.11/mDNSMacOSX/mDNSMacOSX.c SPSCreateDict()
        #   just make sure Type == 10, see SetSPS()
        'stype': '_sleep-proxy._udp',
        'domain': '', #domainname?
        'host': '', #localhost
        'protocol': mdns.PROTO_INET,  # TODO: Support IP6
        'port': 3535,
    }
)

server = dnsserve.SleepProxyServer(('0.0.0.0', 3535))
server.serve_forever() #dispatches a new dnsserve for every SPS client that sends an NSUPDATE to us

